### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by bealdav** [OCA/delivery-carrier#107]
This branch name is carrier-delivery and modules inside are [base_]delivery_carrier_blabla

It's error prone. Nobody can remember what is the real name.

I suggest to rename carrier-delivery repo by delivery-carrier.

As we had could see when switch from lp: to github:, github manage really well alias repositories.
Then there'll no impact to production environment.

Please thanks to vote.

ping @yvaucher @guewen

**Comment by mourad-ehm** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lasley** [comment]
Agreed. This also matches our naming schema in relation to Odoo modules. Delivery is one & carrier is not, so delivery should be first. 👍

**Comment by yvaucher** [comment]
:+1: 

Where to rename it:

OCA/maintainer-tools

```
$ack carrier-delivery
build/lib.linux-x86_64-2.7/tools/branches.yaml
87:  #- github: git@github.com:OCA/carrier-delivery.git

env/lib/python2.7/site-packages/tools/branches.yaml
87:  #- github: git@github.com:OCA/carrier-delivery.git

tools/oca_projects.py
108:    'logistics': ['carrier-delivery',

tools/repos_with_ids.txt
37:99|github.com/OCA/carrier-delivery

tools/branches.yaml
87:  #- github: git@github.com:OCA/carrier-delivery.git
```
- in all README.rst of all version of delivery-carrier modules
- badges in README.md
- transifex project to rename ?
- registration on apps.odoo.com
- runbot ?
- links on odoo-community.org

Most of this can be done later as github does the alias but in the long term we want to rename it everywhere. Am I missing something? I guess that coverall and travis will follow the change without issue.

**Comment by pedrobaeza** [comment]
Good recompilation. I don't miss anything

**Comment by bealdav** [comment]
ok then, who push the button ?

**Comment by yvaucher** [comment]
I don't have access to those settings I think it's someone of @OCA/board noone else has admin rights on repositories

**Comment by yvaucher** [comment]
By the way robots are starting to do a takeover of the world a member of the board is @oca-transbot 

:grin:

**Comment by pedrobaeza** [comment]
Uhm, PSC people should have also access I think... I'll do it anyway.

**Comment by lasley** [comment]
No settings tab for PSCs:

![image](https://cloud.githubusercontent.com/assets/7397578/19446233/b9c1d0ea-944c-11e6-8f59-519a93e0730b.png)

**Comment by pedrobaeza** [comment]
Renamed!

**Comment by pedrobaeza** [comment]
Please perform the rest of the list, @yvaucher
