### ISSUE TITLE
generic module name for carrier

### ISSUE THREAD

**Issue by bealdav** [OCA/delivery-carrier#108]
@hparfr made a generic module for carrier but with a dependency on base_delivery_carrier_label. 

It has a https://pypi.python.org/pypi/roulier an API for package delivery

you can see there:

https://github.com/akretion/delivery-carrier/tree/8-roulier/delivery_carrier_label_roulier

We want to propose it for OCA but we want rename module shorter. Here are some options:
- delivery_carrier_roulier
- delivery_roulier

For my part the last is the best (shorter), then for other module delivery_carrier_mycarrier

Are you ok ?

**Comment by lasley** [comment]
IMO `delivery_carrier_label_roulier` matches the other modules made for generating labels via a service. 

`delivery_roulier` tells me that I can perform all delivery functions using this, which is not the case from what I can see?

**Comment by bealdav** [comment]
@lasley ok maybe carrier_roulier for the common module
then 
carrier_roulier_mycarrier
carrier_roulier_mycarrier_dropoff_site

I would avoid delivery_carrier_label_roulier_mycarrier_dropoff_site. 
What do you think ?

**Comment by lasley** [comment]
Maybe I'm unclear on exactly what roulier is doing. Is this a connector framework to multiple carriers?

**Comment by bealdav** [comment]
Yes it's a framework to deal with multiple carriers sharing an api.
![api](https://cloud.githubusercontent.com/assets/1853434/19488355/d315a1a0-9566-11e6-8024-55d42dc5e889.png)

Some other carriers are in other branch WIP

Here is the api in odoo side
https://github.com/akretion/delivery-carrier/blob/8-roulier/delivery_carrier_label_roulier/stock.py#L81-L146

**Comment by hparfr** [comment]
> Maybe I'm unclear on exactly what roulier is doing. Is this a connector framework to multiple carriers?

Yes

I've updated the documentation here : https://github.com/akretion/roulier/blob/develop/README.md 
It's still work in progress.

**Comment by lasley** [comment]
Thanks for the elaboration. Seems to me that this would control all aspects of the delivery operation, so you would be safe in `delivery_roulier`. 

I question though if maybe `connector_roulier` is a more suitable name, even without a dependency on the connector library. We did something similar with our [connector_easypost](https://github.com/laslabs/odoo-connector-easypost/tree/9.0/connector_easypost), although that does have connector depends.

@pedrobaeza - you're way better with naming. Thoughts on this?

**Comment by hparfr** [comment]
> Odoo Connector is a powerful framework to develop any kind of **bi-directional** connector between Odoo and any other software or service. 
> [Source](https://github.com/OCA/connector)

Roulier is (_currently_) not intended to be bi-directional. It makes synchronous calls.

I did not read connector_easypost source, but why do you need the dependency against connector ?

**Comment by lasley** [comment]
[`connector`](https://github.com/oca/connector) provides an abstract asynchronous (or synchronous if you so choose) framework between disparate systems that is significantly better than I could hope to create without months of dedicated effort & a budget exceeding into the tens of thousands of dollars. 

It includes everything from abstract mappers, abstract adapter interface, logging, record monitoring for instant pushes, record dependency handling for import/export, and a load of other features that are incredibly hard to get right - particularly from an interface agnostic perspective.

Note that while the framework supports bi-directional, it does not impose any limitations on the developer. You can choose to push info, pull info, or both - either async or sync, dependent on whatever business logic is relevant in your particular context.

I highly recommend looking at the connector framework, then possibly implementing an abstract shipping connector - similar to [`connector_dns`](https://github.com/laslabs/infrastructure-dns/tree/da81be8fac2597f27dad2c9a6a6a6a1efd6a3739/connector_dns) (and opposed to my proprietary connector_easypost)

**Comment by bealdav** [comment]
@lasley Yes Connector is a really nice solution, the swiss knife of connections

But for carriers we want share as most as possible code with the python community to share dev and maintenance
I'm not sure that we can do it with connector as odoo module. 

Maybe a future split of connector could change that (as I know @guewen'll split connector in 2 modules for v10 )

Thanks for your support of connector

**Comment by bguillot** [comment]
`delivery_roulier_mycarriername`  seems good enough to me

any other opinions ?
