### ISSUE TITLE
Github page not available

### ISSUE THREAD

**Issue by yvaucher** [OCA/delivery-carrier#117]
@OCA/board 

For this repository we generate the branch https://github.com/OCA/delivery-carrier/tree/gh-pages

This branch was displaying a doc on http://oca.github.io/carrier-delivery
But this later url show nothing.

Could an OCA owner check this repository has the same settings for github page than on https://github.com/oca/connector ?

Thanks

**Comment by dreispt** [comment]
http://oca.github.io/delivery-carrier/ is working for me.

**Comment by yvaucher** [comment]
@dreispt thanks that might have been temporary. Sorry for the noise. I'm closing it.
