### ISSUE TITLE
[RFC] stock_package_rate: Rates in Dispatch Wizard

### ISSUE THREAD

**Issue by lasley** [OCA/delivery-carrier#144]
This module will add a view of the Dispatch Rates provided in `stock_picking_delivery_rate` from within the Packaging wizard in a stock picking ([`delivery.view_quant_package_form_save`](https://github.com/odoo/odoo/blob/10.0/addons/delivery/views/delivery_view.xml#L250)).

As it stands right now, the packaging wizard contains the ability to select a package type to be used for dispatch, and manually select the shipping weight if necessary.

Below the shipping weight, the rates will be listed. An onchange will also be provided to watch for changes in the packaging/weight and adjust accordingly.

Simple enough of a module I think. I feel like this should be a common need though, so I feel like I'm missing something. 

How does everyone else solve the problem of letting a user select which shipping rate should be used against a specific package? Are you all directing users to enter that in the `Additional Info` page of the stock picking before actually packing the order and just shipping all via the same carrier/method? Or is there a module/workflow I'm missing?

**Comment by pedrobaeza** [comment]
What I have in a custom private module, as it was very customer specific (with boxes and pallets), is to add new delivery grid possibilities: to take number of these packagings as criteria for the delivery grid, and to value them by this number. This way, the rate is on the delivery carrier. All of this extending delivery standard module.

**Comment by lasley** [comment]
It sounds like in your instance all of the boxes and pallets in a shipment would be the same size? Or does the grid look something like this:

| Package Type | Shipping Weight | Qty | Carrier Service | Rate |
|--------------|-----------------|-----|-----------------|------|
| 11x5x5       | 40              | 2   | UPS Ground      | $$$  |
| 11x5x5       | 10              | 1   | UPS Air         | $$$  |
| Pallet       | 1000            | 5   | UPS Freight     | $$$  |

**Comment by lasley** [comment]
Also, these are pre-packed packages? So you would first go through the "Put in Pack" for relevant items, then perform this grid workflow?

**Comment by pedrobaeza** [comment]
Exactly. I put the kind of packaging like you put. The limitation is that on each delivery, you can't mix types.

**Comment by pedrobaeza** [comment]
As said, it's very custom, as they keep these 3 "UoM" simultaneous on each sale order line: kg, boxes of type X, and pallets of type Y.

**Comment by lasley** [comment]
Ahhhh got it, so you're able to perform the pack and ship operations all from within this grid due to the pre-defined criteria. Thanks for the insight Pedro - I think it confirms my plans too, which is pretty much the same thing except not in a batch.

I like your idea of a grid though - the put in pack wizard is incredibly cumbersome IMO. Lots of clicking around for an inventory agent. My mind is kind of exploding trying to figure out how to abstract it out though, so I think I'm going to write it in a ticket for later investigation so I don't end up in a different rabbit hole 😆
