### ISSUE TITLE
method call generate_labels() doesn't match signature

### ISSUE THREAD

**Issue by bealdav** [OCA/delivery-carrier#15]
It seems there is a difference between this call
https://github.com/OCA/carrier-delivery/blob/7.0/base_delivery_carrier_label/stock.py#L148
        return self.generate_labels(cr, uid, ids, context=context)

and this method
https://github.com/OCA/carrier-delivery/blob/7.0/base_delivery_carrier_label/stock.py#L105
    def generate_labels(self, cr, uid, ids, tracking_ids=None, context=None):

Personally and I do not use 'action_generate_carrier_label'.
Which args should change ?

Thanks

**Comment by guewen** [comment]
I don't see any difference. `tracking_ids` is an optional kwargs, that is not used in `action_generate_carrier_label` because it has no meaning there (because it is called from a button on the picking, the user cannot choose tracking_ids there).

**Comment by bealdav** [comment]
ok you're right.
