### ISSUE TITLE
Partner Shipper (similar to partner_delivery_zone)

### ISSUE THREAD

**Issue by kittiu** [OCA/delivery-carrier#194]
Hi, we have created a module (after searching from here) called partner_shipper. It is a simple module, that allow a partner to tie to multiple shippers (company that do the shipping).  On Sales Order, user select 1 shipper from multiple available shippers specific to the partner. The shipper from SO will be passed on to both Delivery Order and Invoice.

https://github.com/ecosoft-odoo/addons/tree/12.0/partner_shipper

Is this module welcome to be in OCA/delivery-carrier? it is quite generic. If so, we can do the PR.

**Comment by pedrobaeza** [comment]
I try to understand the goal of this module. Why not using the standard `delivery` feature for that?

**Comment by kittiu** [comment]
Yes it is similar and not add enough value. I will close this.
