### ISSUE TITLE
delivery_multi_destination bugs

### ISSUE THREAD

**Issue by eversatis** [OCA/delivery-carrier#210]
I found two bugs for app delivery_multi_destination bugs in odoo 12.

1. If you add more than two multi destination shipping methods, the website will return 500 internal error on checkout page.

2. The Multi destination shipping methods with shipping rates do not show in the Delivery Method selection list on backend order. So you can not  quote the shipping rate from the multi destination shipping method if you want create an order manually in back end.

Thank you in advance for any  contributor who will solve this.

**Comment by pedrobaeza** [comment]
@frankmiao2015 please specify each of the issues you have found in a separate issue, with detailed steps to reproduce the problem. Provided info is not enough.

Any way, `delivery_multi_destination` is only for backend. There's no `website_delivery_multi_destination` for providing support to website, so first one might not qualify.

Closing this issue waiting for the other detailed 2.
