### ISSUE TITLE
12.0 always shipping cost added in sale 

### ISSUE THREAD

**Issue by jado95** [OCA/delivery-carrier#223]
If i set  'False' on setting parameters 'delivery_auto_refresh.auto_add_delivery_line' the delivery line is added but is not correct

**Comment by rousseldenis** [comment]
@pedrobaeza @cubells

**Comment by pedrobaeza** [comment]
Try to put `0`, not `False`.

**Comment by jado95** [comment]
So, with 0 is ok.
If i add manually the delivery with button 'Add to Order', on validation picking, the delivery will not add on Sale Order.
If i do not add manually delivery on sale order, on validation of picking the delivery is added on Sale Order.
Does Is Correct?
