### ISSUE TITLE
Branches removal

### ISSUE THREAD

**Issue by rousseldenis** [OCA/delivery-carrier#278]
@yvaucher I see two branches on this repo where you push commits.

In order to clean, I will delete them as they should not appear on OCA side.

Ok for you ?

**Comment by yvaucher** [comment]
you mean postlogistics-doc and gh-pages? no please don't remove them.

**Comment by yvaucher** [comment]
Unless it was about 11.0-ocabot-merge-pr-155-by-yvaucher-bump-no nevertheless which I just removed.

The 2 other branches are there for documentation.

**Comment by rousseldenis** [comment]
Yes, I've understood, but why not putting those docs somewhere (maybe wiki or ...) ?

**Comment by yvaucher** [comment]
Till now, this is the way we provide extensive documentation for some OCA modules.

Other examples are OCA/geospatial and OCA/connector

The wiki was probably not existing at that time. But I don't know if it supports multi language.

EDIT: rewording
