### ISSUE TITLE
[13.0] delivery_free_fee_removal behavior not coherent with standard behavior

### ISSUE THREAD

**Issue by guewen** [OCA/delivery-carrier#306]
The module `delivery_free_fee_removal` allows to ignore the creation of delivery lines when they have a zero amount.
I migrated it in 13.0 (#280) but overlooked changes in version 13.0 which bring new problems.

The delivery line becomes more important in 13.0 (probably to simplify the UI/UX):

* the carrier field is not shown, as the delivery line contains the delivery method's name
* the button "add shipping" becomes "update shipping" only when the computed field "delivery_set" is True, which is True when a delivery line exists
* for users, removing the delivery method is done by deleting the delivery line

Summarizing: the delivery line is now the indicator of the delivery method. If we remove the free lines, we have these side-effects:

* we don't know if and which method has been selected
* the button "update shipping" is never shown, only "add shipping"
* no way to remove a delivery method

One way to solve this would be to change the `delivery_set` computed field and show the carrier field: I don't like it because it brings back complexity and different ways for users to work with delivery methods.

IMO a better solution, since 13.0, would be to:

* keep the 0 lines but maybe show them in gray
* ignore the 0 lines when creating the invoice (set `qty_to_invoice` to 0)
* hide delivery lines in sale reports

Any thoughts? 
@cubells @pedrobaeza ?

Also, should I rename the module to `delivery_free_fee_hide` if I make these changes?

**Comment by pedrobaeza** [comment]
Let me try and think options and come back to you.

**Comment by guewen** [comment]
@pedrobaeza here's the proposal I mentioned: #307
