### ISSUE TITLE
14 base_delivery_carrier_label refactore

### ISSUE THREAD

**Issue by florian-dacosta** [OCA/delivery-carrier#322]
Since Odoo has implemented some carrier label modules I think there are issues with the module base_delivery_carrier_label.
Indeed, when we install it, we have 2 buttons.
"Shipping Label" (`def action_generate_carrier_label`) implemented by `base_delivery_carrier_label`
"Send to Shipper" (`def send_to_shipper`) implemented by Odoo, but really usefull with carrier label enterprise modules.

I don't use yet these module in recent version...but it seems to me that it is impossible for the end user to understand this !
Also, not using the native button, we have to override some native method to avoid problems (done in carrier modules, like here : https://github.com/OCA/delivery-carrier/blob/12.0/delivery_carrier_label_postlogistics/models/delivery.py#L224)

So, I'd like to change this, and I'd like to know the opinion of the main contributors.

Option 1) We display one button or the other depending on the carrier
I saw that we display the OCA button only if we have a carrier code. There are no reason to have a code with an enterprise carrier since it is an OCA field.
We could hide the native Odoo button if we have a code. (If not good enought, we could eventually add a flag on carrier or something
But we still would have a different workflow depending if the carrier is implemented by odoo or OCA

Option 2) Always hide the Odoo native button, override the `send_shipping` method.
=> Module is then totally incompatible with enterprise modules.
I guess this is not the way to go...

Option 3) Remove the OCA button and make `base_delivery_carrier_label` use the `send_to_shipper` method/button.
The main issues I see are : 
- label is printed automatically at picking transfer. Not sure it is an issue, but it is a change for the OCA modules.
- Odoo SA always manage label with a price features, which is not the case at all in the OCA module.
For example, in France, until now, we never got the price from carrier webservice and some just don't have this feature or we don't even want/need this feature.
So Odoo always post a message of this kind on picking : `Shipment sent to carrier %(carrier_name)s for shipping with tracking number %(ref)s<br/>Cost: %(price).2f %(currency)s`
which make no sense if the price is always 0 because not returned by carrier api.
So we would need to patch it one way or another to remove the price part.
(but from what I see, it is the case anyway if we have the Get Rate and Create Shipment set on `integration_level` field...so it is kind of a problem already since it is the default value when choosing a carrier `delivery_type`)

I in favor or solution 3) since it is the more compatible with Odoo enterprise.
And I don't really see big issues in doing it. At least if a user user enterprise and oca modules, it will really have only one workflow.

Concretly, we would get rid of `action_generate_carrier_label` / `_compute_show_label_button` / `generate_default_label` / `generate_shipping_labels` / `_get_packages_from_picking` (no relation with the subject it seems it becames useless, we could just ask for the field `package_ids`)
maybe bypass `send_to_shipper` if any shipping label exists (this way make it possible to generate labels before picking processing)

I'd make the change only in v14 as the module is still no migrated and it will break modules depending on it.
Any opinon @yvaucher @bealdav @sebastienbeau @hbrunn ?

**Comment by hbrunn** [comment]
when I worked on this, the carriers I implemented created labels in the same request where you fetch the tracking number, so it was more convenient to implement https://github.com/OCA/delivery-carrier/blob/12.0/base_delivery_carrier_label/models/delivery_carrier.py#L28 (the oca way) for them. That's why I also added https://github.com/OCA/delivery-carrier/blob/12.0/base_delivery_carrier_label/models/stock_picking.py#L31 to allow other addons to hide this button, which _ups and _paazl do. So I think 3 is indeed the way to go, but why worry about the pricing? So ypu get a price of 0, what's the problem?

**Comment by florian-dacosta** [comment]
About the pricing, it is just really weird to have a message saying you did ship some goods for 0 euros when it is totally untrue.
It is one more thing that would confuse the enduser a lot I think.

**Comment by yvaucher** [comment]
@florian-dacosta There are similar intern discussion at camptocamp about refactoring the OCA modules (but for v13) to be more in line with Odoo core. I didn't had the chance to dive in the Odoo delivery modules yet in latest versions but I know this will raise the interest of @jgrandguillaume and @chroi

**Comment by yvaucher** [comment]
@florian-dacosta one issue I see we could have is in case of pre-printing of shipping label. For one of our customer for returned merchandise they pre-print the labels for incoming pickings. Not sure if Odoo supports this in their enterprise modules.

My point is that we have to make sure a done picking is not a requirement to call the printing. But we could manage that with an other button with other visibility rules if it's correctly factored. I hope the Odoo code on shipping labels is not yet an other monolith.
