### ISSUE TITLE
[12.0] Field duplicated: number_of_packages

### ISSUE THREAD

**Issue by sergiocorato** [OCA/delivery-carrier#336]
If the modules `delivery_package_number` and `stock_picking_delivery_info_computation` are installed together, the field appears twice.
See:
https://github.com/OCA/delivery-carrier/blob/726d786c73a7b7a5dc0ad8d75eeb8871b22f4ab6/delivery_package_number/models/stock_picking.py#L9
https://github.com/OCA/delivery-carrier/blob/726d786c73a7b7a5dc0ad8d75eeb8871b22f4ab6/stock_picking_delivery_info_computation/models/stock_picking.py#L10

Perhaps `stock_picking_delivery_info_computation` is a more complete alternative of `delivery_package_number` , so I can close the issue.

**Comment by chienandalu** [comment]
Well, they don't exclude each other. In `stock_picking_delivery_info_computation` is added for convenience and has not much to do with the rest of the features while `delivery_package_number` is an specific module that revolves around that field. You're free to use either one or them both :wink:

**Comment by sergiocorato** [comment]
Thanks
