### ISSUE TITLE
[14.0] [RunBot] Can't make Colissimo (delivery_roulier_laposte_fr) work

### ISSUE THREAD

**Issue by delkano** [OCA/delivery-carrier#407]
I've tried to:

- get into your runbot ( http://3499001-14-0-257892.runbot2-2.odoo-community.org/ )
- go to the shop
-  add an item to the cart
-  set up a (fake) French address
-  hit "Process Checkout",
-  the delivery methods are correctly listed:

![image](https://user-images.githubusercontent.com/6650309/130103308-574ba5cc-076d-41a6-aa77-cc9f69b8d471.png)

- But then the fee estimation is shown as an ever turning wheel, and a popup error appears:

```Odoo Server Error
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/.repo_requirements/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/website_sale_delivery/controllers/main.py", line 30, in update_eshop_carrier
    order._check_carrier_quotation(force_carrier_id=carrier_id)
  File "/.repo_requirements/odoo/addons/website_sale_delivery/models/sale_order.py", line 64, in _check_carrier_quotation
    if res.get('success'):
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'get' 
```

I had the same error on my own system when I tried to install the module.

I don't know if there is some configuration missing or it's an actual bug.

**Comment by pedrobaeza** [comment]
I don't see "Colissimo" in the module list of this repo. Which module are you talking about?

**Comment by delkano** [comment]
Oh sorry, yes. Colissimo belongs to "La Poste, it's the module delivery_roulier_laposte_fr

**Comment by pedrobaeza** [comment]
OK, I let then the contributors of such module to answer, but a minimum credentials should put in any module of this nature.

**Comment by delkano** [comment]
I see that the maintainer is @florian-dacosta 

I will try to find a fix on my own, and if I find anything I'll post it here.

**Comment by florian-dacosta** [comment]
Hello @delkano 
I checked and it seem we have an incompatibility for now with the `website_sale_delivery` module.
Indeed, the module for la poste is made to generate carrier labels, but it does not get the price of the delivery. Laposte does not provide this or at least, it has not been implemented.

I'll make a PR to avoid the failure in that case and I'll check if the README has to be improved to specify clearly that the module does not provide a feature to get the price from the carrier.
I think such a module https://github.com/OCA/delivery-carrier/tree/13.0/delivery_price_method could be usefull to still get the price from a grid in that case.

**Comment by borisNG** [comment]
hi @florian-dacosta is delivery_roulier_laposte_fr any update on the plugin ? or do you have any clue on how to make it work ?  i'm really stuck on that and since there is no implementation for methods like rate_shipment or send_shipping.

**Comment by borisNG** [comment]
@delkano do you found a solution to make it work properly ?

**Comment by delkano** [comment]
Sorry, I just downgraded to Odoo 13 in the end, since I was having trouble with several plugins

**Comment by florian-dacosta** [comment]
Hello @borisNG 
I use `delivery_roulier_laposte_fr` to generate carrier labels without problem.
The send_shipping method is actually implemented via the `delivery_roulier` module.
The rate feature is not part of the module though, only the label generation.

**Comment by borisNG** [comment]
ah okay thanks @florian-dacosta
