### ISSUE TITLE
Porting base_delivery_carrier_files to v8

### ISSUE THREAD

**Issue by kirca** [OCA/delivery-carrier#45]
Our company is planning on porting base_delivery_carrier_files. I saw in one of the commits (https://github.com/OCA/carrier-delivery/commit/dee67b57f9ec4f5d01c6c1c85b7e40126e5f6ab5) that some work was already done on it. I'm writing just to know whether someone is already doing this so that we don't duplicate work already done. Thanks for the info.

**Comment by kkarolis** [comment]
Starting to make a port of it to v8.

**Comment by yvaucher** [comment]
@kirca Ok the someone was me. In fact this wasn't a port it was just getting some changes from 7.0 branch to 8.0. So nothing done yet.

@kkarolis good to know. Thanks

**Comment by yvaucher** [comment]
https://github.com/OCA/carrier-delivery/pull/47
