### ISSUE TITLE
[14.0]delivery_free_fee_removal doesnt work if sale order is locked

### ISSUE THREAD

**Issue by thorneindustries** [OCA/delivery-carrier#513]
## Module
delivery_free_fee_removal

## Describe the bug

If setting     group_auto_done_setting is true, sale orders are locked after action_confirm. 

This line
```
 delivery_lines = self.order_line.filtered(
            lambda line: line.order_id.state == "sale" and line. 
```
in sale_order.py should probably be

```
 delivery_lines = self.order_line.filtered(
            lambda line: line.order_id.state in ("sale","done") and line.
```

## To Reproduce

1. Enable locking sale from settings after completion
2. Create a sales order with a delivery
3.

**Comment by pedrobaeza** [comment]
Yes, good point. Can you do the pull request changing that?
