### ISSUE TITLE
Schenker TLS V1.2

### ISSUE THREAD

**Issue by hildickethan** [OCA/delivery-carrier#514]
I have this email from DB Schenker relating to the TLS version

```
Dear DB Schenker web service user,

We would like to connect with you regarding the following eSchenker web service(s) that you are using:

BookingWebServiceV1_1
GermanLabelServiceV1 
BookingParcelRestApi_V1
BookingParcelWebserviceV1
BranchWS_V1
TrackingWebsService_V1

There are upcoming technical changes to these web services which might impact you.

What is the change?
We will upgrade our security and only allow TLSv1.2 or higher to connect with our web services.
For more information on TLS, please see the following article - https://en.wikipedia.org/wiki/Transport_Layer_Security

When is the change planned for?
We will upgrade our security at the end of July 2022.
```

From what I could find `zeep` uses V1.2+ by default, so I don't think there needs to be a change, but I want to confirm with @chienandalu , I assume one of your clients will also have received something like this

If everything is ok then feel free to close the issue

**Comment by chienandalu** [comment]
If understood well, it should be no issue.

**Comment by hildickethan** [comment]
Ok I thought so, I will leave it as is and we will see when the change rolls around if anything happens
Thanks
