### ISSUE TITLE
Migrating delivery_carrier_multi_zip to 14.0

### ISSUE THREAD

**Issue by rizzel** [OCA/delivery-carrier#527]
**Is your feature request related to a problem?**

No

**Describe the solution you'd like**

The module to also be available on the `14.0` branch in addition to the `13.0` branch.

**Describe alternatives you've considered**

None

**Additional context**

It is a small module and we use it in our installation on Odoo 14 from the `13.0` branch for now. Can I help somehow to get it also on the `14.0` branch? The tests run successful and it seems no code changes are needed.

**Comment by pedrobaeza** [comment]
You can fo the pull request following the migration guide:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0.

**Comment by rizzel** [comment]
I created a pull request  #528 so this can probably be closed.

Thank you.
