### ISSUE TITLE
Split base_delivery_carrier_label

### ISSUE THREAD

**Issue by florian-dacosta** [OCA/delivery-carrier#537]
Hello,
`base_delivery_carrier_label` is not used as a dependency for all oca carrier module. I think it is a shame not to have some consistency between oca modules on this matter, because that becomes a problem when using multiple carriers that works differently (not user friendly + harder to override in case of custom behavior).

The most important example, IMHO, is the `carrier.account` model.
In some module like delivery_ups_oca (probably multiple others) the carrier account is set directly on the delivery method, on others, based on base_delivery_carrier_label, it is managed with the `carrier.account` model from `base_delivery_carrier_label`.

I believe it is important that all modules use `carrier.account` for the following reasons : 

- No `delivery.carrier` duplication in case we use multiple carrier accounts.
  In case of multi company instance for example, it allows you to share the `delivery.method `between companies
  In case of complicated use case you may have multiple account for a same carrier depending on custom criterias. In this case, you definitely don't want to duplicate the `delivery.carrier`
  
- no carrier account duplication : some times we have multiple delivery method for 1 carrier (depending on the service...) and it is easier to have a separated object for this, to avoid duplicating the account information on each delivery method.

- possibility tu customize the way to get the account information for all carrier instead of overriding the same for each carrier...

- we basically have at least an account number/password as common field for all carrier account, no duplicating this fields for each carrier make is easier, for instance we have a generic carrier_account_environment module instead of having one by carrier...

I am probably missing other pros arguments, and I don't really see any cons ?

The reason for not using `base_delivery_carrier_label` as a dependency I was told, if I remember well, was because it had too much features, it added too much maintenance burden, etc
That is why, I'd like to propose to split this module for version 16.

As I see it, base_delivery_carrier_label has 3 main features/areas : 
1) carrier account model and (overridable) method to choose the right one
2) Possibility to have option for a delivery carrier with possibility to choose specific option for a picking and not another...
3) miscellaneous helpers that could help/standardize the carrier modules (special model to store labels, store parcel number on pack, auto generate pack if missing, etc)

So we would have 3 modules
1) delivery_carrier_account => dependency of all OCA carrier modules
2) delivery_carrier_option => optional for carrier modules that want to use it
3) delivery_carrier_helper => optional for carrier modules (I would make it mandatory as well, but I guess it is more controversial so let's forget this)

What do you think ? If the module is splitted in this way, would you be ok to make `delivery_carrier_account` a mandatory dependency for all carrier modules ?
@pedrobaeza @sebalix @sonhd91 @yvaucher

**Comment by pedrobaeza** [comment]
Each carrier has its "login" fields. Sometimes, they are 2, other times 3, and very diverse, so I see difficult to get s common ground for all.

About the label dependency, a lot of carriers send you already the pdf/zpl to print, so that base is also not needed IMO.

**Comment by florian-dacosta** [comment]
Hello @pedrobaeza 
Thanks for taking the time to answer. I know that the login fields may differ, but the fact of sharing 2 fields is the least important advantage! For me, the main point is that an account has no link with a delivery method, so adding the login fields on `delivery.method`

1) For 1 carrier, we can have multiple delivery methods. For example, one for delivering in the local company country, 1 for Europe, 1 for the rest of the world. Some times different delivery method for different services (j+2, j+3, dangerous goods, fresh goods or anything you can imagine).
If for 1 carrier you use 10 delivery method, but you have only 1 login, it makes no sense to duplicate these login/password 10 times.

2) On the contrary, you can have multiples account, for 1 delivery method.
I gave before the multi company case, that I have, a delivery method shared between companies, but account is different per company. 
Same as before, it makes no sense to duplicate the same delivery method just because you have a different account.
On this matter, a use case I have, which is not linked to multi company case : 
The company A ships good to its own customers (b2c), and it also ship goods for the customer of other companies B and C , but using these companies B&C branding on the label (white label dropshipping)
=> to achieve this, we need a different carrier account by company that uses our company A as dropshipper.
We definitly don't want to duplicates all delivery method of all carriers...to manage thise case.

3) The lest advantage is to share fields login/password, which are usually used. So that we can have only 1 module 'carrier_account_environment' for example.
Let's see with the carriers I am most used to : 
laposte france => login/password => perfect, nothing to do
chronopost france => login/password/sub account : we have to add the optional field for sub account, but not really usefull to be environment dependant in case of testing.
geodis : login/password/customer_id => we add one field geodis_customer_id, which is not necessary to be environment dependant for testing
dpd : login/password/customer id => we add one field dpd_customer_id which need to be environment dependent for testing.
gls france : login/password/customer_id => we add one field gls_customer_id , which is not needed to be environment dependent for testing.
So, using all these carriers, I only need to have by module carrier_environment_module + a module to manage the customer_id as environment dependent for DPD, nothing more.

It is not incredible as advantage, but still better to share the login/password which are almost always needed and are usually the one which need to be environment dependent.
For all additional fields, we add it with the carrier prefix so that the view is always adapted to show only the needed fields depending of the carrier. (example : https://github.com/akretion/delivery-carrier/blob/14-gls-rest-webservice/delivery_roulier_gls_fr/views/account_carrier_view.xml#L12)

Finally, about the label dependency, I am not sure I understand what you mean. 
We usually need to send the format we need for the carrier webservice to send the label in the right format. But, in my experience, the format differs really a lot between carriers, and the field can't really be shared between carriers. 
So I don't use the field file_format defnied on carrier_account, for me it could be removed because I always re-define it for the carrier : https://github.com/akretion/delivery-carrier/blob/14-gls-rest-webservice/delivery_roulier_gls_fr/models/carrier_account.py#L11).
Well maybe you were not talking about that, not sure !

So, I really think the item 1 et 2 I listed are super valid, and I don't see any reason it would be better to stick putting these fields on `delivery.carrier`, (other than changing this would require to migrate some data for the customers, which is ok between main odoo version).
But I'd be glad to understand why the present way (login fields on `delivery.carrier)` would be better. **I insist, the main goal is not to share the login fields, it is just a nice to have to avoid too much glue module with server_environment in case it is needed, the main goal, is to share and have a different model than delivery.carrier`**

Anyway, as you must have seen, I have extracted this `carrier.account` model from `base_delivery_carrier_label` for v16, so it is easy to use for each carrier module without adding useless features. I can't force anyone to depend on it, but at least it will be easy to do so !

**Comment by pedrobaeza** [comment]
I want to avoid a big dependency chain and failure points. That's why I'm a bit reluctant. But my colleague @chienandalu is a fan of this idea, so let's go with it. Comments on the PR.
