### ISSUE TITLE
[14.0] fix delivery_cttexpress tests

### ISSUE THREAD

**Issue by mmequignon** [OCA/delivery-carrier#611]
In the `delivery_cttexpress` module, tests are calling the external service.
For some reason, this service isn't (or wasn't, haven't checked since) responding, and makes every build fails.

A unit test shouldn't directly call external services.
There's a few tools to avoid such calls, like
[vcrpy](https://vcrpy.readthedocs.io/), [responses](https://github.com/getsentry/responses/blob/master/README.rst) or [requests-mock](https://requests-mock.readthedocs.io/en/latest/).
As vcrpy is already in the `test-requirements.txt`, I think it would be the best choice here.

Ping @chienandalu

**Comment by pedrobaeza** [comment]
This is an old debate and I don't agree: mocking this makes that any change in the real API will make the module to fail, do that's the reason for the tests, to detect this.

Anyway, try now, that it will be ok. There are some glitches sometimes.

**Comment by rousseldenis** [comment]
@mmequignon @pedrobaeza Re launching the eternal debate, but blocking merges now...

**Comment by rousseldenis** [comment]
I will put it in rebel modules, safer.

**Comment by rousseldenis** [comment]
> I will put it in rebel modules, safer.

In fact, no, won't change anything

**Comment by pedrobaeza** [comment]
This happens very occasionally. Let's try again.

**Comment by lmignon** [comment]
It's an old and annoying debate but being stuck by unstable external system sucks.

**Comment by lmignon** [comment]
We are more often blocked by this type of problem than by a change of api of the external service. So the cost of this approach is much higher for the whole community. Therefore there is no benefit in not adopting the best practice of not calling an external api in unit tests and replacing these calls with a mock system implementing the api as specified by the external system.

**Comment by john-herholz-dt** [comment]
Any solution for that? A PR from me is blocked by that, even though it is a simple module with no tests needed.
