### ISSUE TITLE
TNT Italy

### ISSUE THREAD

**Issue by esafocus** [OCA/delivery-carrier#629]
Unfortunately it doesn't work with TNT Italia, do you know if it's my problem or is the module not supported by TNT Italia?

**Comment by francesco-ooops** [comment]
@esafocus what is not working? which flow is not correct in your opinion? what is the expecrted result?

please follow the steps to reproduce / current behavior / required behavior template for reporting bugs

**Comment by esafocus** [comment]
These are the steps I take:
- I enter the credentials of the TNT courier:
username
Password
Accounts
    I enable production
- I create a quote and confirm it
In the delivery order, I make sure that the TNT courier is selected;
- I validate the document and the delivery email and the text saying that the delivery has been sent to the carrier with a FALSE tracking number are generated
- I check in the courier's reserved area and I have no shipment

IMPORTANT NOTE:
I tried entering the wrong credentials to understand if odoo is really talking to the courier and is not giving errors, so I assume there is a communication problem.
The odoo logs report nothing out of the ordinary

**Comment by francesco-ooops** [comment]
@esafocus sorry but the goal is to try to reproduce the described behavior on runbot., and to understand which module is not working as expected. 

The instructions above are too generic to reproduce (eg: enter the credentials where specifically? select courier where?)

You can find links to runboat for this repo [here](https://runboat.odoo-community.org/webui/builds.html?repo=OCA/delivery-carrier&target_branch=14.0), can you reproduce it in video and specify which module is not working as expected?

**Comment by esafocus** [comment]
I attach the video.
In the end I would expect the shipment registered on my TNT account and tracking number
https://github.com/OCA/delivery-carrier/assets/92449751/c74b03e0-9d6a-4644-95fa-b2619a7c1161

**Comment by esafocus** [comment]
I attach the video.
In the end I would expect the shipment registered on my TNT account and tracking number

https://github.com/OCA/delivery-carrier/assets/92449751/0c81ff2d-8140-4018-935b-d9666ad9baa2

**Comment by esafocus** [comment]
I attach the video.
In the end I would expect the shipment registered on my TNT account and tracking number

https://github.com/OCA/delivery-carrier/assets/92449751/57d5a469-fe59-4ea6-86f0-29b18e78b8b1

**Comment by francesco-ooops** [comment]
ok so we're talking about delivery_tnt_oca I suppose! Which version are you testing on?

**Comment by esafocus** [comment]
I'm using version 14.0+e-20230513 (Enterprise Edition)

**Comment by esafocus** [comment]
yes the module delivery_tnt_oca. Sorry if I wasn't clear, I thought you understood from the title
