### ISSUE TITLE
delivery_package_number bug module when creating a backorder

### ISSUE THREAD

**Issue by angelgarciadelachica** [OCA/delivery-carrier#676]
## Module
delivery_package_number

## Describe the bug
We have detected a bug in the delivery_package_number module when creating a backorder.

## To Reproduce
**Affected versions**:

1. Create a sales order containing at least one storable product and quantity greater than 1, example 10.
2. Confirm the sales order.
3. Go to the created delivery.
4. Enter the 'Number of Packages' in the 'Additional Info' tab, example 2.
5. Enter the packages in the 'Done' column less than 'Reserved', example 2.
6. Click on Validate and click on 'Generate Backorder' or 'No backorder' .

**Expected behavior**
If we go again to the tab 'Additional Info' the number of packages is 1 (incorrect) instead of 2 (correct).

**Additional context**
While trying to solve it we have detected that the problem is caused by the repeated execution of the _compute_number_of_packages function that recalculates the number of packages based on package_ids and sets the Number of Packages to 1 if there are no package_ids.

## Proposal
We propose the following changes to the delivery_package_number module to fix the bug:

- Create a boolean field that will appear next to the 'Number of Packages' to be able to switch between inserting the number manually or having it automatically calculated based on the package_ids. This way we avoid recalculating the 'Number of Packages' if it is in manual mode.
- On the other hand, if the company has disabled the 'Packages' in the Inventory settings, by default the option will be manual.
- In addition, we will also add a Boolean field in the 'Operation Type' to set whether it is calculated automatically or manually by default depending on the 'Type of Operation'. In this way, we will always be able to choose from the picking whether the 'Number of Packages' is inserted manually or automatically but, depending on the 'Type of Operation', there will be a default option.

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten @luis-ron

**Comment by HaraldPanten** [comment]
@pedrobaeza @chienandalu that might be interesting for you 👍

**Comment by pedrobaeza** [comment]
My colleague is on holidays. I can't say right now.

**Comment by HaraldPanten** [comment]
> My colleague is on holidays. I can't say right now.

No problem. We'll wait few weeks. THX!

**Comment by HaraldPanten** [comment]
@chienandalu @pedrobaeza Is it OK for you having a look at this?

We'll manage the IMP/FIX

THX!

**Comment by pedrobaeza** [comment]
Reading the issue, I would see 2 problems:

- The recomputation if backorders. But I don't get why it's recomputed. Please check depends of the compute.
- To put package=1 if no package configuration on the system. Why the default=1 is bad?

**Comment by angelgarciadelachica** [comment]
Hi @pedrobaeza
Each time a Delivery is created, the number of packages field is recomputed. This is correct and should default to 1. 

The problem is that when a backorder is created, a new delivery is created with the remaining quantities which causes it to be recomputed for both delivery notes instead of just the one created. So in the two delivery notes (the validated and the new one with the remaining units), the number of packages is set to 1.

THX!

**Comment by pedrobaeza** [comment]
For avoiding that, you should pass a context on backorder creation, put `@api.depends_context`, and don't recompute package in such case.

**Comment by angelgarciadelachica** [comment]
Hi @pedrobaeza,

I tried to do it using the @api.depends_context, but it doesn't work. 
When a backorder is created the compute is called twice:

- A first one, when the delivery note is validated with the quantities done. In this case we could control it with @api.depends_context, since we can add parameters to the context.
- A second time, after executing the process function, which is called by clicking on the button 'Create backorder'. In this case the context is cleared and executed with the two backorders. Which causes the number of packages in both deliveries to be set to one. 

Is there any way to avoid the last compute execution?

THX!

**Comment by pedrobaeza** [comment]
Please put a PR developing a test that fails on such case, and I will experiment in my local with the test to see the best solution.

**Comment by angelgarciadelachica** [comment]
Hi @pedrobaeza
I have put a PR with the tests showing the issue -> PR #694 
THX!

**Comment by pedrobaeza** [comment]
Fixed in #696
