### ISSUE TITLE
CTT Express module

### ISSUE THREAD

**Issue by rousseldenis** [OCA/delivery-carrier#806]
@pedrobaeza For several days, the connection seems impossible with the API.

See: 

https://github.com/OCA/delivery-carrier/actions/runs/8937112296/job/24548717691?pr=805

https://github.com/OCA/delivery-carrier/actions/runs/8967049459/job/24623776476

Could you get in touch with the provider to solve it ? As we try to merge some PR's and we don't want to take time to do back and forth ... Thanks

**Comment by rousseldenis** [comment]
@chienandalu

**Comment by pedrobaeza** [comment]
We will check tomorrow at OCA days.

**Comment by pedrobaeza** [comment]
Disabled in all the branches.
