### ISSUE TITLE
Questions on package_ids

### ISSUE THREAD

**Issue by hparfr** [OCA/delivery-carrier#81]
Hi,

I started the implementation of Laposte WS (according to 2016 specifications).
While digging in the sources, I don't understand this : 

``` python
    def generate_labels(self, package_ids=None):
        """ Generate the labels.
        A list of tracking ids can be given, in that case it will generate
        the labels only of these packages.
        """
        label_obj = self.env['shipping.label']

        for pick in self:
            if package_ids:
                shipping_labels = pick.generate_shipping_labels(
                    package_ids=package_ids
                )
```

https://github.com/OCA/carrier-delivery/blob/9.0/base_delivery_carrier_label/stock.py#L120

If there is multiple picks in self and package_ids is not None, where is the check to exclue all the package_ids which doesn't belongs to pick ?

And more globally, what's the point of package_ids in params ?
It means we can deliver a part of a picking with one carrier and the rest with another one ?

**Comment by guewen** [comment]
Hi,

The use case is: you want to generate labels for only some of the packages of a picking, and generate labels for the remaining packages later.

The API has changed a bit since, but in 7.0 it was used here: https://github.com/OCA/carrier-delivery/blob/467c5cc2d60c43b1ef3037ae6b83d375b99d3b72/delivery_carrier_label_dispatch/wizard/generate_labels.py#L108-L111 (it generates the labels of the packages which are in the picking dispatch only).

**Comment by hparfr** [comment]
Thanks for this answer.

In the code you refere, you have always 1 picking and 0 or 1 pack.
But it can lead to issues if there is call with 2 pickings and 1 pack.

**Comment by guewen** [comment]
I see your point, is it something that might happen? having a package cross-pickings? If yes, then yes it should be handled better...

**Comment by hparfr** [comment]
In terms of code quality, it's always better if the API is obvious or well documented for starters like me.

About the business cases : 
- a package cross-picking -> we have this need for some of our clients. They have customer who buys on a regulary basis, and they want put in the same package goods from differents sale orders. 
- multiple package for one picking -> never encoutered yet, but I was thinking of this use case when you want different levels of services (insurance, urgent, fragile, voluminous) for the same order.
  Like part of the sale order by aircraft for the small items and the rest by cargo.
