### ISSUE TITLE
Right repository for carriers

### ISSUE THREAD

**Issue by jans23** [OCA/delivery-carrier#825]
I'm wondering which is the right repository for shipping carriers which are not available in internationally. I see [this DHL module](https://github.com/OCA/l10n-germany/pull/141) in l10n-germany, and I see delivery_correos_express #813 in this repository which seems to be available in Spain only. This seems inconsistent to me. @pedrobaeza you [once suggested](https://github.com/OCA/delivery-carrier/pull/482#issuecomment-1415226865) to land national carriers in the particular l10n repository. Is there a general best practice to pick the right repository?

**Comment by pedrobaeza** [comment]
Correos Express is available both in [Spain](https://www.correosexpress.com/) and [Portugal](https://www.correosexpress.pt/). That's why it's here.
