### ISSUE TITLE
[9] refactorisation of base_default_label

### ISSUE THREAD

**Issue by hparfr** [OCA/delivery-carrier#85]
Hi folks,

These days tere is some work against branch 9.0, it's still time to do heavy refactors before freezing the code.

For new commers, it's quite hard to understand how to integrate / develop a new carrier.
I think there is 3 types of methods :
- helpers methods (like get_weight)
- logic methods (glue between UI and carrier's specific methods)
- carrier's specific methods (fetch relevant data, then call webservice and so on)

I suggest to make a clear distinction between these methods by : 
- better naming 
- write the type in docstrings
- move all carrier specific method in separate files or modules.

What do you think ?

**Comment by yvaucher** [comment]
Maybe you want to comment this in #72  ?
