### ISSUE TITLE
[14.0] Install easypost dependencies

### ISSUE THREAD

**Issue by antoniodavid** [OCA/delivery-carrier#869]
I have created a new addon [868](https://github.com/OCA/delivery-carrier/pull/868) to integrate the connection with EasyPost, but the GitHub Actions are not passing, as it fails to install the dependency in the required version.

The error is in the Python version installed, which is installing 3.6.

![image](https://github.com/user-attachments/assets/a5918aed-38a5-491f-acf0-6efd74bb0a31)

**Comment by rousseldenis** [comment]
That's why you shouldn't fix the easypost package version as pip will try to find the latest one for the current Python version in use in environment (version 9.3.0 is for Python >= 3.7)

**Comment by rousseldenis** [comment]
@antoniodavid you should set "easypost<8" in external dependencies

**Comment by antoniodavid** [comment]
Thank you for responding so quickly @rousseldenis, but I would like to know why the version being installed for Odoo 14 is 3.6 when the recommended version is 3.8.5.

**Comment by rousseldenis** [comment]
> Thank you for responding so quickly @rousseldenis, but I would like to know why the version being installed for Odoo 14 is 3.6 when the recommended version is 3.8.5.

In fact, this has always be debated. If I remember correctly, we decided to run our tests instance with the minimum version required by Odoo which is for v14 : https://github.com/odoo/odoo/blob/14.0/setup.py#L58

**Comment by antoniodavid** [comment]
Thank you very much, I will see how I can fix it.
