### ISSUE TITLE
[16] delivery_auto_refresh doesn't update if customer is changed

### ISSUE THREAD

**Issue by Gelojr** [OCA/delivery-carrier#873]
## Module
delivery_auto_refresh

## Describe the bug
delivery_auto_refresh doesn't update if customer is changed

## To Reproduce
**Affected versions**:
16 At least
1. Create a new SO
2. Add a customer and save. The delivery method will be added if it is set in the customer.
3. Modify the customer, add another customer with a different delivery method, and save. The delivery method will not be updated. 

**Expected behavior**
The delivery method should be updated if the customer is changed.
**Additional context**
https://www.loom.com/share/fc71fd79c4c84ea689bd73858ed6c405?sid=eb7b80ad-0401-4cb2-afa4-6e23709d86e0
@moduon MT-6943

**Comment by Gelojr** [comment]
https://youtu.be/l3rRGeNVoqc?si=R6KiVefQHqUc8Df6

**Comment by rafaelbn** [comment]
Hello,

@jbaudoux @simahawk Do you agree if we solve this issue?

Thanks
Regards
