### ISSUE TITLE
ZPL recovery mode

### ISSUE THREAD

**Issue by bealdav** [OCA/delivery-carrier#94]
Ping @yvaucher @guewen @hparfr @sebastienbeau 

What do you think to add generic method to use this webservice for our customers just in case of the printer is out of order ?

http://labelary.com/service.html

With 
GET http://api.labelary.com/v1/printers/{dpmm}/labels/{width}x{height}/{index}/{zpl}

you can add pdf attachement to picking.

Thanks for your reply.

**Comment by yvaucher** [comment]
@bealdav For postlogistics, output format can be selected. It can be zpl, png or pdf already
